# Book Settings
title: "Data Science Process using CRISP-DM - Translate Version 1.0"
author: "raul-data-scientist"
logo: https://tse2.mm.bing.net/th/id/OIG3.QJbeEUe_IsQJM.U7sSh_?w=1024&h=1024&rs=1&pid=ImgDetMain
copyright: "All credits to Bitlabs Academy"
bibtex_reference_style: author_year  # or label, super, \supercite

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

repository:
  url: https://github.com/Raul-Data-Scientist/data-science-crisp-dm-EnglishVersion
  branch: notebooks
  path_to_book: book

# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  google_analytics_id: "G-VND61T1FVN" # (Need to create one and change)

# Exeuction Settings
execute:
  execute_notebooks: "off"
  allow_errors: true

launch_buttons:
  colab_url: "https://colab.research.google.com"
  thebe: true

bibtex_bibfiles:
  - references.bib
